### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by BiteFoo** [tiann/eadb#12]
大佬你好，我用了eadbv0.1.4+debianfs-arm64-full.tar.gz 搭了一个环境，在执行eadb shell 的阶段发现网络不能用，使用adb shell可以使用网络。

手机 `google pixel3  arm64 内核是4.9.210-gdee0d123b122-ab6570413` 

设置rootfs 
```sh
./eadb --ssh root@192.168.41.207 -p 22225 prepare -a debianfs-arm64-full.tar.gz

```
安装正常

登录上来
```sh
./eadb --ssh root@192.168.44.207 -p 22225  shell
```
然后安装工具时网络就不能访问
```sh
apt update
Err:1 http://mirrors.ustc.edu.cn/debian bullseye InRelease
  Temporary failure resolving 'mirrors.ustc.edu.cn'
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/bullseye/InRelease  Temporary failure resolving 'mirrors.ustc.edu.cn'
W: Some index files failed to download. They have been ignored, or old ones used instead.

```
使用`ping` 后
```sh
root@localhost:/# ping baidu.com 
ping: baidu.com: Temporary failure in name resolution
```
当前使用adb shell 能正常使用手机网络。
```sh
blueline:/ # ping baidu.com
PING baidu.com (220.181.38.251) 56(84) bytes of data.
64 bytes from 220.181.38.251: icmp_seq=1 ttl=52 time=42.9 ms
64 bytes from 220.181.38.251: icmp_seq=2 ttl=52 time=59.0 ms
```

**Comment by SeeFlowerX** [comment]
修改/etc/passwd的_apt的65534为3003

- https://askubuntu.com/questions/910865/apt-get-update-fails-on-chroot-ubuntu-16-04-on-android
- https://blog.seeflower.dev/archives/111/

**Comment by tiann** [comment]
https://github.com/joelagnel/adeb/blob/master/buildstrap#L56

**Comment by BiteFoo** [comment]
> 修改/etc/passwd的_apt的65534为3003
> 
> * https://askubuntu.com/questions/910865/apt-get-update-fails-on-chroot-ubuntu-16-04-on-android
> * https://blog.seeflower.dev/archives/111/

我试试这个，感谢
