### ISSUE TITLE
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"

### ISSUE THREAD

**Issue by df13954** [tiann/eadb#20]
```
Unpack of rootfs successful!
oriole:/ # /data/eadb/run /data/eadb/debian
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
/bin/bash[10]: syntax error: unexpected '('
1|oriole:/ #
```

环境：
pixel6，Android13，内核Linux version 5.10.149-android13-4-gebdbc9fbe2e2-dirty (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6), LLD 14.0.7) #1 SMP PREEMPT Mon Feb 27 10:44:09 UTC 2023

**Comment by SeeFlowerX** [comment]
大概率是你下载到amd64架构的了

**Comment by df13954** [comment]
> 大概率是你下载到amd64架构的了

啊，果然是，累了没有看仔细。我马上换。

**Comment by df13954** [comment]
下错包了~~
