### ISSUE TITLE
eadb prepare 本地文件逻辑异常

### ISSUE THREAD

**Issue by SeeFlowerX** [tiann/eadb#4]
用ssh，必须先把压缩包放到`/data/eadb/debian/data/eadb/deb.tar.gz`

然后才能

`eadb --ssh root@ip prepare -a path/to/archive(本地路径)`

然后提示找不到`device-*`

- https://github.com/tiann/eadb/blob/0832f6ec8c469de948fa9f8b4d609bd0ab1fb169/src/cli.rs#L133

这是因为这些文件实际解压到

- `/data/eadb/debian/data/eadb/device-unpack`

原因是

- https://github.com/tiann/eadb/blob/0832f6ec8c469de948fa9f8b4d609bd0ab1fb169/src/cli.rs#L192
- https://github.com/tiann/eadb/blob/68b95925b0b26094735c034626a306e4683c554f/src/ssh.rs#L75
- https://github.com/tiann/eadb/blob/02be99058e5897b0bb9e37ff04039a4e2aace127/src/constants.rs#L19

ssh的push这里把路径拼接为`{EADB_ROOTFS_DIR}/{EADB_DIR}`，但是后面脚本的操作都是基于`EADB_DIR`，最终导致`chmod +x device-*`命令异常

**Comment by tiann** [comment]
https://github.com/tiann/eadb/commit/93d0e375e6802b029faff4e90b7a2d03a782dc94
