### ISSUE TITLE
Android 模拟器运行问题

### ISSUE THREAD

**Issue by StarHeartHunt** [tiann/eadb#6]
环境为 AVD 启动的 Android 12.0 Pixel 2，使用 63e6e2e 的 [Actions 构建版本](https://github.com/tiann/eadb/actions/runs/2539857897)。

在 `eadb prepare` 后执行 `eadb shell`，产生如下报错后连接被关闭
```
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
CANNOT LINK EXECUTABLE "/system/bin/ndk_translation_program_runner_binfmt_misc_arm64": library "libicu.so" not found: needed by /system/lib64/libharfbuzz_ng.so in namespace (default)
```

**Comment by tiann** [comment]
你可能需要自行构建 x86_64 的 image，Android 模拟器里面的 ndk_translation 会把 arm 指令转译成 x86 的，但很可能在 chroot 出来的 debian 系统不生效

**Comment by tiann** [comment]
你可以试下这个  https://github.com/tiann/eadb/actions/runs/2541671847

**Comment by StarHeartHunt** [comment]
> 你可以试下这个 https://github.com/tiann/eadb/actions/runs/2541671847

使用这个版本后可以成功进入 SSH了，感谢大佬。

不过没有找到演示视频里一样的 vmlinux 路径，可能需要出厂 Android 12 的真机才有完整的 eBPF 支持？

**Comment by SeeFlowerX** [comment]
可能需要一些内核头文件？

内核是4.19，我编译通过后，执行报错，提示没有开启`CONFIG_IKHEADERS`

```bash
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
```

不过提示可以指定内核源代码目录，根据bcc文档，可以在编译前设置`BCC_KERNEL_SOURCE`环境变量指定内核源代码目录

下载了手机内核的源代码，指定了重新编译测试，还是会找不到部分头文件，后来确认是结构不一样

然后发现安卓内核源代码一般都有个`kernel_headers.py`，感觉有办法生成bcc需要的一致的源代码结构

这样的话可能可以适配更多4.x系列内核的手机

- https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/picasso-r-oss/kernel_headers.py

**Comment by tiann** [comment]
> 不过没有找到演示视频里一样的 vmlinux 路径，可能需要出厂 Android 12 的真机才有完整的 eBPF 支持？

我看过 Android 12 模拟器的内核配置，从参数上看是可以的；如果有问题，可以把日志或者输出啥的贴出来。
