### ISSUE TITLE
GLIBC_  XXX not found

### ISSUE THREAD

**Issue by CHU-YUN-FEI** [tiann/eadb#7]
![image](https://user-images.githubusercontent.com/45117488/175233093-5be225df-6ac7-4117-b291-12b610ca1971.png)
![image](https://user-images.githubusercontent.com/45117488/175233285-27482544-a458-44c4-adc6-bb3be799df77.png)

**Comment by tiann** [comment]
可以尝试自己编译

**Comment by tiann** [comment]
用静态编译的版本应该可以解决：https://github.com/tiann/eadb/actions/runs/2547458316

**Comment by SeeFlowerX** [comment]
要用ubuntu22.04编译，不要尝试自己搞glic，容易把系统搞崩。。

**Comment by tiann** [comment]
我用 musl libc 编译了一个 static executable，用那个，不依赖 glibc

**Comment by SeeFlowerX** [comment]
这样就太好了
