### ISSUE TITLE
eadb v0.1.3 + debianfs-full.tar.gz 环境，编译 bpftrace 报错

### ISSUE THREAD

**Issue by shen330** [tiann/eadb#9]
维术带佬你好，我跟着教程在手机上用 eadb v0.1.3 + debianfs-full.tar.gz  搭起 linux 环境，想简单体验一下 bpftrace 的效果

apt install bpftrace 后，执行 readme 中的展示命令会报错，参考直播时提到过 bcc 源码中的 tracing 路径问题，猜测应该是 bpftrace 源码里也写死了 /sys/kernel/debug/tracing 导致的，所以 fork 并修改了 bpftrace 的源码并 clone 到回来，尝试在手机上源码编译

目前是在源码编译仅修改 tracing 路径后的 bpftrace 过程中，make -j8 时报错
![image](https://user-images.githubusercontent.com/8542638/175314435-9d838e7b-2b4a-4e31-ac63-84b59fc1b71c.png)

检查了报错代码中，对应函数的调用如下， 传递了 3 个参数
```
  init_disassemble_info(&info, stdout, fprintf_nop);
```

但是从手机 linux 环境的  /usr/include/dis-asm.h  文件中查看导出的 init_disassemble_info 函数有 4 个参数，所以报错了
```c++
/* Method to initialize a disassemble_info struct.  This should be
   called by all applications creating such a struct.  */
extern void init_disassemble_info (struct disassemble_info *dinfo, void *stream,
				   fprintf_ftype fprintf_func,
				   fprintf_styled_ftype fprintf_styled_func);

/* For compatibility with existing code.  */
#define INIT_DISASSEMBLE_INFO(INFO, STREAM, FPRINTF_FUNC, FPRINTF_STYLED_FUNC)  \
  init_disassemble_info (&(INFO), (STREAM), (fprintf_ftype) (FPRINTF_FUNC), \
			 (fprintf_styled_ftype) (FPRINTF_STYLED_FUNC))
```

对这个方向的知识储备比较少，现在不知道该从哪里入手才能正常编译出 bpftrace 了，请 带佬 帮忙解答，非常感谢

**Comment by tiann** [comment]
给一下你的编译步骤

**Comment by shen330** [comment]
我是参考的 bpftrace 的源码编译文档 https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#building-bpftrace-1

拉代码
git clone https://github.com/shen330/android_bpftrace.git 
- 只改了 tracing path 
![image](https://user-images.githubusercontent.com/8542638/175337760-5a3e88c1-60dd-4a25-9a39-9e258849eb54.png)

sudo apt-get install -y \
  bison \
  cmake \
  flex \
  g++ \
  git \
  libelf-dev \
  zlib1g-dev \
  libfl-dev \
  systemtap-sdt-dev \
  binutils-dev \
  libcereal-dev \
  llvm-12-dev \
  llvm-12-runtime \
  libclang-12-dev \
  clang-12 \
  libgtest-dev \
  libgmock-dev \
  asciidoctor

mkdir bpftrace/build; cd bpftrace/build;

cmake -DCMAKE_BUILD_TYPE=Release ..

make -j8 ， 执行 make 后出现上面的错误

**Comment by tiann** [comment]
应该是依赖装错了，重新整个环境，仅安装这里面的[依赖](https://github.com/tiann/eadb/commit/3dc592c86d57286373dd61ccbf7398fe9b62d54c) 再试。
